### ISSUE TITLE
osu! ripple and special mode screen effects

### ISSUE THREAD

**Issue by Ladcan** [TheEggo58/eternity-rls#3]
osu! cookies still ripples while on another tab and the ripple doesn't do anything until user returns to the tab.
special mode flash effect overlays the top gui

**Comment by TheEggo58** [comment]
Could you please elaborate on what you mean by "tabs"?

**Comment by Ladcan** [comment]
Browser tabs. you'll see them at the top of the browser's window after opening the browser.

Here is a picture of what I mean.
![Screenshot (11)](https://user-images.githubusercontent.com/55308129/161407805-75bb7324-1cd2-46db-a3a6-ead5d2f4e912.png)

**Comment by TheEggo58** [comment]
> Browser tabs. you'll see them at the top of the browser's window after opening the browser.
> 
> Here is a picture of what I mean.

Ah, i see.
That's actually caused by a browser feature which freezes inactive tabs to save up on ram usage and not the game.
