### ISSUE TITLE
Combobursts overflowing randomly, possible bootstrap issue?

### ISSUE THREAD

**Issue by TheEggo58** [TheEggo58/eternity-rls#4]
Combobursts sometimes clone on loop and cause the game to hang up, maybe the value isn't being reset on startup? (Don't know why this keeps happening, afaik this only happens on std)

**Comment by asherlr23** [comment]
Try this
![image_2022-06-08_140348987](https://user-images.githubusercontent.com/73479844/172686127-67ba423c-0497-4a85-8209-09bb44962b6e.png)

**Comment by asherlr23** [comment]
Better version

![image_2022-06-08_141015623](https://user-images.githubusercontent.com/73479844/172687196-3d4c1d17-703e-4a88-8781-c8bcf2991d1f.png)

**Comment by TheEggo58** [comment]
Fixed this in the new cuttingedge branch.
